"""Centralized project configuration values.

Edit this file to match your wiring and runtime preferences.
"""

from __future__ import annotations

# Motor driver (L298N) GPIO pins
MOTOR_IN1 = 17
MOTOR_IN2 = 27
MOTOR_IN3 = 22
MOTOR_IN4 = 23
MOTOR_ENA = 18
MOTOR_ENB = 24

# Optional PWM values (0-100)
MOTOR_PWM_FREQUENCY_HZ = 1000
MOTOR_DEFAULT_SPEED = 70
MOTOR_LEFT_TRIM = 0
MOTOR_RIGHT_TRIM = 0
MOTOR_START_BOOST_DUTY = 85
MOTOR_START_BOOST_SEC = 0.08
LEFT_MOTOR_INVERT = False
RIGHT_MOTOR_INVERT = False

# Ultrasonic sensor pins (HC-SR04)
ULTRASONIC_TRIG_PIN = 5
ULTRASONIC_ECHO_PIN = 6
ULTRASONIC_TIMEOUT_SEC = 0.04
OBSTACLE_THRESHOLD_CM = 20.0
OBSTACLE_HYSTERESIS_CM = 2.0
ULTRASONIC_POLL_INTERVAL_SEC = 0.08

# Camera settings
CAMERA_INDEX = 0
FRAME_WIDTH = 640
FRAME_HEIGHT = 480
# GUI live preview size (camera_process sends this resolution to the dashboard)
PREVIEW_WIDTH = 640
PREVIEW_HEIGHT = 480
FRAME_QUEUE_SIZE = 2
CAMERA_POLL_INTERVAL_SEC = 0.03

# Process timing / queue controls
VISION_POLL_INTERVAL_SEC = 0.03
DECISION_POLL_INTERVAL_SEC = 0.02
MOTOR_POLL_INTERVAL_SEC = 0.02
AUDIO_POLL_INTERVAL_SEC = 0.1
QUEUE_GET_TIMEOUT_SEC = 0.1
DECISION_COMMAND_DEBOUNCE_SEC = 0.20
MOTOR_COMMAND_HOLD_SEC = 0.25
MOTOR_IDLE_STOP_SEC = 0.40

# Audio
AUDIO_PIN = 25
BEEP_FREQUENCY_HZ = 1100
BEEP_DURATION_SEC = 0.25
BEEP_COOLDOWN_SEC = 0.7

# Debug/testing behavior
ENABLE_DEBUG_LOGS = True

# Vision fallback detector (contours/boxes)
VISION_MIN_CONTOUR_AREA = 1100
VISION_BOX_CENTER_DEADZONE = 0.15  # fraction of frame width
VISION_STOP_AREA_RATIO = 0.22

# Optional YOLO object detection
YOLO_ENABLED = False
YOLO_MODEL_PATH = "models/yolov8n.pt"
YOLO_CONFIDENCE = 0.45
YOLO_IMAGE_SIZE = 416
